[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.0",
    "cachetools>=5.5.0",
    "requests>=2.32.3",
]

[tool.uv]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
